## Python для анализа данных
### Домашнее задание NumPy

Дан массив, содержащий баллы слушателей курса по английскому языку за вступительный экзамен. Слушатели распределены по 15 группам по 10 человек.

In [1]:
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

### Задание 1

Посчитать, сколько слушателей получили 0 за вступительный экзамен.

In [7]:
### YOUR CODE HERE ###
sc1 = scores.copy()
print((sc1 == 0).sum())

13


### Задание 2

Посчитать, сколько слушателей получили балл выше 50.

In [8]:
### YOUR CODE HERE ###

print((sc1 > 50).sum())

64


### Задание 3

Посчитать, сколько человек получили балл не ниже 50, но не выше 70.

In [14]:
### YOUR CODE HERE ###

print(((sc1 >= 50) & (sc1 <= 70)).sum())

26


### Задание 4

Определить, в какой группе средний балл за вступительный экзамен выше.

In [50]:
### YOUR CODE HERE ###

# print(len(sc1.mean(axis=1)))
print(sc1.mean(axis=1).argmax()+1)

10


### Задание 5

Сохранить баллы слушателей выше 0 в массив `nonzero`. 

In [39]:
### YOUR CODE HERE ###

nonzero = sc1[np.where(sc1 > 0)]
nonzero

array([ 20,  40,  56,  80,   5,  25,  27,  74,   1,  98,  67, 100,   8,
        56,  34,  82, 100,   7,  78,  54,  23,  79, 100,  42,  95,  83,
        51,  50,  47,  23, 100,  94,  25,  48,  38,  77,  90,  87,  41,
        89,  52,   5,  17,  28,  99,  32,  18,  21,  18,  29,  31,  48,
        62,  76,  22,   6,  65,  78,  43,  22,  38,  88,  94, 100,  77,
        28,  39,  41,  81,  45,  54,  98,  12,  66,  88,  44,  55, 100,
        12,  11,  17,  70,  86,  96,  56,  23,  32,  49,  70,  80,  20,
        24,  76,  50,  29,  40,   3,   2,   5,  11,  33,  63,  28,  40,
        51, 100,  98,  87,  22,  30,  16,  54,  78,  12,  25,  35,  10,
        19,  67, 100,  88,  24,  33,  47,  56,  62,  34,  77,  53,  50,
        89,  70,  72,  56,  29,  15,  20])

### Задание 6

Используя массив `nonzero`, определить минимальный балл за вступительный балл по всем группам.

In [40]:
### YOUR CODE HERE ###

print(nonzero.min())

1


### Задание 7

Выбрать из массива `nonzero` только те значения, которые соответствуют продвинутому уровню знания языка – баллу за экзамен выше 80. Сохранить полученный результат в массив `advanced`. В заданиях 8-10 нужно работать с массивом `advanced`.

In [41]:
### YOUR CODE HERE ###

advanced = nonzero[np.where(nonzero > 80)]
advanced

array([ 98, 100,  82, 100, 100,  95,  83, 100,  94,  90,  87,  89,  99,
        88,  94, 100,  81,  98,  88, 100,  86,  96, 100,  98,  87, 100,
        88,  89])

### Задание 8

Определить размерность массива `advanced`.

In [42]:
### YOUR CODE HERE ###

print(advanced.ndim)

1


### Задание 9

Определить форму массива `advanced`.

In [43]:
### YOUR CODE HERE ###

print(advanced.shape)

(28,)


### Задание 10

Определить общее число элементов в массиве `advanced`.

In [44]:
### YOUR CODE HERE ###

print(advanced.size)

28


### Задание 11

На основе исходного массива `scores` создать булев массив `sto`, где `True` соответствует баллам за экзамен, равным 100, а `False` – всем остальным баллам. 

In [46]:
### YOUR CODE HERE ###

sto = scores == 100
sto

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False,  True,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, 

### Задание 12

На основе исходного массива `scores` вывести на экран оценки слушателей первых семи групп (включительно, должны быть 7 списков оценок).

In [49]:
### YOUR CODE HERE ###

scores[:7]

array([[ 20,  40,  56,  80,   0,   5,  25,  27,  74,   1],
       [  0,  98,  67, 100,   8,  56,  34,  82, 100,   7],
       [ 78,  54,  23,  79, 100,   0,   0,  42,  95,  83],
       [ 51,  50,  47,  23, 100,  94,  25,  48,  38,  77],
       [ 90,  87,  41,  89,  52,   0,   5,  17,  28,  99],
       [ 32,  18,  21,  18,  29,  31,  48,  62,  76,  22],
       [  6,   0,  65,  78,  43,  22,  38,  88,  94, 100]])